global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["prometheus:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]
  - job_name: "sport"
    static_configs:
    - targets: [ "svc-sport:8080" ]


